baseURL = 'https://chaomai.github.io/'
languageCode = 'en-us'
title = "chaomai's-blog"
theme = 'hugo-theme-stack'
hasCJKLanguage = true

pagination.pagerSize = 10
enableEmoji = true
enableRobotsTXT = true

[author]
  name = 'chaomai'

[permalinks]
  post = '/:year/:month/:day/:filename/'

[menu]
  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 10
  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 20
  [[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 30
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 40

[markup]
  [markup.highlight]
    noClasses = false

[services]
  [services.googleAnalytics]
    ID = 'G-LD2SMTGQE7'

[Params]
  [Params.Article]
    math = true
    toc = true
    license.enabled = true
  [Params.Footer]
    since = 2014
  [Params.Sidebar]
    avatar.src = 'static/images/default_avatar.jpg'
